/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentRewardsRouteImport } from './routes/student.rewards'
import { Route as StudentPointsRouteImport } from './routes/student.points'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentFilesRouteImport } from './routes/student.files'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentAssistantRouteImport } from './routes/student.assistant'
import { Route as StudentAchievementsRouteImport } from './routes/student.achievements'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminScanRouteImport } from './routes/admin.scan'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQuestionBankRouteImport } from './routes/admin.question-bank'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMapsRouteImport } from './routes/admin.maps'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminFilesRouteImport } from './routes/admin.files'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminBackupsRouteImport } from './routes/admin.backups'
import { Route as AdminAssistantRouteImport } from './routes/admin.assistant'
import { Route as AdminArchiveRouteImport } from './routes/admin.archive'
import { Route as AdminApiRouteImport } from './routes/admin.api'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as StudentExamsIndexRouteImport } from './routes/student.exams.index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin.students.index'
import { Route as AdminExamsIndexRouteImport } from './routes/admin.exams.index'
import { Route as StudentExamsIdRouteImport } from './routes/student.exams.$id'
import { Route as ApiPublicFcmDispatchRouteImport } from './routes/api/public/fcm-dispatch'
import { Route as AdminStudentsIdRouteImport } from './routes/admin.students.$id'
import { Route as AdminExamsAiRouteImport } from './routes/admin.exams.ai'
import { Route as AdminExamsIdRouteImport } from './routes/admin.exams.$id'
import { Route as AdminAiUsageRouteImport } from './routes/admin.ai.usage'
import { Route as AdminAiQuotasRouteImport } from './routes/admin.ai.quotas'
import { Route as AdminAiMappingRouteImport } from './routes/admin.ai.mapping'
import { Route as StudentExamsIdIndexRouteImport } from './routes/student.exams.$id.index'
import { Route as AdminExamsIdIndexRouteImport } from './routes/admin.exams.$id.index'
import { Route as StudentExamsIdTakeRouteImport } from './routes/student.exams.$id.take'
import { Route as StudentExamsIdStartRouteImport } from './routes/student.exams.$id.start'
import { Route as StudentExamsIdResultRouteImport } from './routes/student.exams.$id.result'
import { Route as ApiPublicV1StudentsRouteImport } from './routes/api/public/v1.students'
import { Route as ApiPublicV1StatsRouteImport } from './routes/api/public/v1.stats'
import { Route as ApiPublicV1LeaderboardRouteImport } from './routes/api/public/v1.leaderboard'
import { Route as AdminStudentsQuickCodeRouteImport } from './routes/admin.students.quick.$code'
import { Route as AdminStudentsIdAnalyticsRouteImport } from './routes/admin.students.$id.analytics'
import { Route as AdminExamsMapNewRouteImport } from './routes/admin.exams.map.new'
import { Route as AdminExamsIdResultsRouteImport } from './routes/admin.exams.$id.results'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentRewardsRoute = StudentRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPointsRoute = StudentPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFilesRoute = StudentFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssistantRoute = StudentAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAchievementsRoute = StudentAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => StudentRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScanRoute = AdminScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionBankRoute = AdminQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapsRoute = AdminMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFilesRoute = AdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssistantRoute = AdminAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArchiveRoute = AdminArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const StudentExamsIndexRoute = StudentExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentExamsRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsIndexRoute = AdminExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentExamsIdRoute = StudentExamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentExamsRoute,
} as any)
const ApiPublicFcmDispatchRoute = ApiPublicFcmDispatchRouteImport.update({
  id: '/api/public/fcm-dispatch',
  path: '/api/public/fcm-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsAiRoute = AdminExamsAiRouteImport.update({
  id: '/exams/ai',
  path: '/exams/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsIdRoute = AdminExamsIdRouteImport.update({
  id: '/exams/$id',
  path: '/exams/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiUsageRoute = AdminAiUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminAiRoute,
} as any)
const AdminAiQuotasRoute = AdminAiQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => AdminAiRoute,
} as any)
const AdminAiMappingRoute = AdminAiMappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => AdminAiRoute,
} as any)
const StudentExamsIdIndexRoute = StudentExamsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentExamsIdRoute,
} as any)
const AdminExamsIdIndexRoute = AdminExamsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminExamsIdRoute,
} as any)
const StudentExamsIdTakeRoute = StudentExamsIdTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => StudentExamsIdRoute,
} as any)
const StudentExamsIdStartRoute = StudentExamsIdStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => StudentExamsIdRoute,
} as any)
const StudentExamsIdResultRoute = StudentExamsIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => StudentExamsIdRoute,
} as any)
const ApiPublicV1StudentsRoute = ApiPublicV1StudentsRouteImport.update({
  id: '/api/public/v1/students',
  path: '/api/public/v1/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1StatsRoute = ApiPublicV1StatsRouteImport.update({
  id: '/api/public/v1/stats',
  path: '/api/public/v1/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1LeaderboardRoute = ApiPublicV1LeaderboardRouteImport.update({
  id: '/api/public/v1/leaderboard',
  path: '/api/public/v1/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsQuickCodeRoute = AdminStudentsQuickCodeRouteImport.update({
  id: '/students/quick/$code',
  path: '/students/quick/$code',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIdAnalyticsRoute =
  AdminStudentsIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminStudentsIdRoute,
  } as any)
const AdminExamsMapNewRoute = AdminExamsMapNewRouteImport.update({
  id: '/exams/map/new',
  path: '/exams/map/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsIdResultsRoute = AdminExamsIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminExamsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai': typeof AdminAiRouteWithChildren
  '/admin/api': typeof AdminApiRoute
  '/admin/archive': typeof AdminArchiveRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRouteWithChildren
  '/student/files': typeof StudentFilesRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/points': typeof StudentPointsRoute
  '/student/rewards': typeof StudentRewardsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/ai/mapping': typeof AdminAiMappingRoute
  '/admin/ai/quotas': typeof AdminAiQuotasRoute
  '/admin/ai/usage': typeof AdminAiUsageRoute
  '/admin/exams/$id': typeof AdminExamsIdRouteWithChildren
  '/admin/exams/ai': typeof AdminExamsAiRoute
  '/admin/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/api/public/fcm-dispatch': typeof ApiPublicFcmDispatchRoute
  '/student/exams/$id': typeof StudentExamsIdRouteWithChildren
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/student/exams/': typeof StudentExamsIndexRoute
  '/admin/exams/$id/results': typeof AdminExamsIdResultsRoute
  '/admin/exams/map/new': typeof AdminExamsMapNewRoute
  '/admin/students/$id/analytics': typeof AdminStudentsIdAnalyticsRoute
  '/admin/students/quick/$code': typeof AdminStudentsQuickCodeRoute
  '/api/public/v1/leaderboard': typeof ApiPublicV1LeaderboardRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/students': typeof ApiPublicV1StudentsRoute
  '/student/exams/$id/result': typeof StudentExamsIdResultRoute
  '/student/exams/$id/start': typeof StudentExamsIdStartRoute
  '/student/exams/$id/take': typeof StudentExamsIdTakeRoute
  '/admin/exams/$id/': typeof AdminExamsIdIndexRoute
  '/student/exams/$id/': typeof StudentExamsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai': typeof AdminAiRouteWithChildren
  '/admin/api': typeof AdminApiRoute
  '/admin/archive': typeof AdminArchiveRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/files': typeof StudentFilesRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/points': typeof StudentPointsRoute
  '/student/rewards': typeof StudentRewardsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/ai/mapping': typeof AdminAiMappingRoute
  '/admin/ai/quotas': typeof AdminAiQuotasRoute
  '/admin/ai/usage': typeof AdminAiUsageRoute
  '/admin/exams/ai': typeof AdminExamsAiRoute
  '/admin/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/api/public/fcm-dispatch': typeof ApiPublicFcmDispatchRoute
  '/admin/exams': typeof AdminExamsIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/student/exams': typeof StudentExamsIndexRoute
  '/admin/exams/$id/results': typeof AdminExamsIdResultsRoute
  '/admin/exams/map/new': typeof AdminExamsMapNewRoute
  '/admin/students/$id/analytics': typeof AdminStudentsIdAnalyticsRoute
  '/admin/students/quick/$code': typeof AdminStudentsQuickCodeRoute
  '/api/public/v1/leaderboard': typeof ApiPublicV1LeaderboardRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/students': typeof ApiPublicV1StudentsRoute
  '/student/exams/$id/result': typeof StudentExamsIdResultRoute
  '/student/exams/$id/start': typeof StudentExamsIdStartRoute
  '/student/exams/$id/take': typeof StudentExamsIdTakeRoute
  '/admin/exams/$id': typeof AdminExamsIdIndexRoute
  '/student/exams/$id': typeof StudentExamsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai': typeof AdminAiRouteWithChildren
  '/admin/api': typeof AdminApiRoute
  '/admin/archive': typeof AdminArchiveRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRouteWithChildren
  '/student/files': typeof StudentFilesRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/points': typeof StudentPointsRoute
  '/student/rewards': typeof StudentRewardsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/ai/mapping': typeof AdminAiMappingRoute
  '/admin/ai/quotas': typeof AdminAiQuotasRoute
  '/admin/ai/usage': typeof AdminAiUsageRoute
  '/admin/exams/$id': typeof AdminExamsIdRouteWithChildren
  '/admin/exams/ai': typeof AdminExamsAiRoute
  '/admin/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/api/public/fcm-dispatch': typeof ApiPublicFcmDispatchRoute
  '/student/exams/$id': typeof StudentExamsIdRouteWithChildren
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/student/exams/': typeof StudentExamsIndexRoute
  '/admin/exams/$id/results': typeof AdminExamsIdResultsRoute
  '/admin/exams/map/new': typeof AdminExamsMapNewRoute
  '/admin/students/$id/analytics': typeof AdminStudentsIdAnalyticsRoute
  '/admin/students/quick/$code': typeof AdminStudentsQuickCodeRoute
  '/api/public/v1/leaderboard': typeof ApiPublicV1LeaderboardRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/students': typeof ApiPublicV1StudentsRoute
  '/student/exams/$id/result': typeof StudentExamsIdResultRoute
  '/student/exams/$id/start': typeof StudentExamsIdStartRoute
  '/student/exams/$id/take': typeof StudentExamsIdTakeRoute
  '/admin/exams/$id/': typeof AdminExamsIdIndexRoute
  '/student/exams/$id/': typeof StudentExamsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/student'
    | '/admin/activity'
    | '/admin/ai'
    | '/admin/api'
    | '/admin/archive'
    | '/admin/assistant'
    | '/admin/backups'
    | '/admin/classes'
    | '/admin/competitions'
    | '/admin/dashboard'
    | '/admin/files'
    | '/admin/leaderboard'
    | '/admin/live'
    | '/admin/maps'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/question-bank'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/rewards'
    | '/admin/scan'
    | '/admin/settings'
    | '/admin/system'
    | '/student/achievements'
    | '/student/assistant'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/files'
    | '/student/messages'
    | '/student/points'
    | '/student/rewards'
    | '/admin/'
    | '/student/'
    | '/admin/ai/mapping'
    | '/admin/ai/quotas'
    | '/admin/ai/usage'
    | '/admin/exams/$id'
    | '/admin/exams/ai'
    | '/admin/students/$id'
    | '/api/public/fcm-dispatch'
    | '/student/exams/$id'
    | '/admin/exams/'
    | '/admin/students/'
    | '/student/exams/'
    | '/admin/exams/$id/results'
    | '/admin/exams/map/new'
    | '/admin/students/$id/analytics'
    | '/admin/students/quick/$code'
    | '/api/public/v1/leaderboard'
    | '/api/public/v1/stats'
    | '/api/public/v1/students'
    | '/student/exams/$id/result'
    | '/student/exams/$id/start'
    | '/student/exams/$id/take'
    | '/admin/exams/$id/'
    | '/student/exams/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/admin/activity'
    | '/admin/ai'
    | '/admin/api'
    | '/admin/archive'
    | '/admin/assistant'
    | '/admin/backups'
    | '/admin/classes'
    | '/admin/competitions'
    | '/admin/dashboard'
    | '/admin/files'
    | '/admin/leaderboard'
    | '/admin/live'
    | '/admin/maps'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/question-bank'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/rewards'
    | '/admin/scan'
    | '/admin/settings'
    | '/admin/system'
    | '/student/achievements'
    | '/student/assistant'
    | '/student/dashboard'
    | '/student/files'
    | '/student/messages'
    | '/student/points'
    | '/student/rewards'
    | '/admin'
    | '/student'
    | '/admin/ai/mapping'
    | '/admin/ai/quotas'
    | '/admin/ai/usage'
    | '/admin/exams/ai'
    | '/admin/students/$id'
    | '/api/public/fcm-dispatch'
    | '/admin/exams'
    | '/admin/students'
    | '/student/exams'
    | '/admin/exams/$id/results'
    | '/admin/exams/map/new'
    | '/admin/students/$id/analytics'
    | '/admin/students/quick/$code'
    | '/api/public/v1/leaderboard'
    | '/api/public/v1/stats'
    | '/api/public/v1/students'
    | '/student/exams/$id/result'
    | '/student/exams/$id/start'
    | '/student/exams/$id/take'
    | '/admin/exams/$id'
    | '/student/exams/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/student'
    | '/admin/activity'
    | '/admin/ai'
    | '/admin/api'
    | '/admin/archive'
    | '/admin/assistant'
    | '/admin/backups'
    | '/admin/classes'
    | '/admin/competitions'
    | '/admin/dashboard'
    | '/admin/files'
    | '/admin/leaderboard'
    | '/admin/live'
    | '/admin/maps'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/question-bank'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/rewards'
    | '/admin/scan'
    | '/admin/settings'
    | '/admin/system'
    | '/student/achievements'
    | '/student/assistant'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/files'
    | '/student/messages'
    | '/student/points'
    | '/student/rewards'
    | '/admin/'
    | '/student/'
    | '/admin/ai/mapping'
    | '/admin/ai/quotas'
    | '/admin/ai/usage'
    | '/admin/exams/$id'
    | '/admin/exams/ai'
    | '/admin/students/$id'
    | '/api/public/fcm-dispatch'
    | '/student/exams/$id'
    | '/admin/exams/'
    | '/admin/students/'
    | '/student/exams/'
    | '/admin/exams/$id/results'
    | '/admin/exams/map/new'
    | '/admin/students/$id/analytics'
    | '/admin/students/quick/$code'
    | '/api/public/v1/leaderboard'
    | '/api/public/v1/stats'
    | '/api/public/v1/students'
    | '/student/exams/$id/result'
    | '/student/exams/$id/start'
    | '/student/exams/$id/take'
    | '/admin/exams/$id/'
    | '/student/exams/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  StudentRoute: typeof StudentRouteWithChildren
  ApiPublicFcmDispatchRoute: typeof ApiPublicFcmDispatchRoute
  ApiPublicV1LeaderboardRoute: typeof ApiPublicV1LeaderboardRoute
  ApiPublicV1StatsRoute: typeof ApiPublicV1StatsRoute
  ApiPublicV1StudentsRoute: typeof ApiPublicV1StudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/rewards': {
      id: '/student/rewards'
      path: '/rewards'
      fullPath: '/student/rewards'
      preLoaderRoute: typeof StudentRewardsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/points': {
      id: '/student/points'
      path: '/points'
      fullPath: '/student/points'
      preLoaderRoute: typeof StudentPointsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/files': {
      id: '/student/files'
      path: '/files'
      fullPath: '/student/files'
      preLoaderRoute: typeof StudentFilesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assistant': {
      id: '/student/assistant'
      path: '/assistant'
      fullPath: '/student/assistant'
      preLoaderRoute: typeof StudentAssistantRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/achievements': {
      id: '/student/achievements'
      path: '/achievements'
      fullPath: '/student/achievements'
      preLoaderRoute: typeof StudentAchievementsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scan': {
      id: '/admin/scan'
      path: '/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AdminScanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/question-bank': {
      id: '/admin/question-bank'
      path: '/question-bank'
      fullPath: '/admin/question-bank'
      preLoaderRoute: typeof AdminQuestionBankRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maps': {
      id: '/admin/maps'
      path: '/maps'
      fullPath: '/admin/maps'
      preLoaderRoute: typeof AdminMapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/files': {
      id: '/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminFilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assistant': {
      id: '/admin/assistant'
      path: '/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AdminAssistantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/archive': {
      id: '/admin/archive'
      path: '/archive'
      fullPath: '/admin/archive'
      preLoaderRoute: typeof AdminArchiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/exams/': {
      id: '/student/exams/'
      path: '/'
      fullPath: '/student/exams/'
      preLoaderRoute: typeof StudentExamsIndexRouteImport
      parentRoute: typeof StudentExamsRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams/': {
      id: '/admin/exams/'
      path: '/exams'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AdminExamsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/exams/$id': {
      id: '/student/exams/$id'
      path: '/$id'
      fullPath: '/student/exams/$id'
      preLoaderRoute: typeof StudentExamsIdRouteImport
      parentRoute: typeof StudentExamsRoute
    }
    '/api/public/fcm-dispatch': {
      id: '/api/public/fcm-dispatch'
      path: '/api/public/fcm-dispatch'
      fullPath: '/api/public/fcm-dispatch'
      preLoaderRoute: typeof ApiPublicFcmDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams/ai': {
      id: '/admin/exams/ai'
      path: '/exams/ai'
      fullPath: '/admin/exams/ai'
      preLoaderRoute: typeof AdminExamsAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams/$id': {
      id: '/admin/exams/$id'
      path: '/exams/$id'
      fullPath: '/admin/exams/$id'
      preLoaderRoute: typeof AdminExamsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai/usage': {
      id: '/admin/ai/usage'
      path: '/usage'
      fullPath: '/admin/ai/usage'
      preLoaderRoute: typeof AdminAiUsageRouteImport
      parentRoute: typeof AdminAiRoute
    }
    '/admin/ai/quotas': {
      id: '/admin/ai/quotas'
      path: '/quotas'
      fullPath: '/admin/ai/quotas'
      preLoaderRoute: typeof AdminAiQuotasRouteImport
      parentRoute: typeof AdminAiRoute
    }
    '/admin/ai/mapping': {
      id: '/admin/ai/mapping'
      path: '/mapping'
      fullPath: '/admin/ai/mapping'
      preLoaderRoute: typeof AdminAiMappingRouteImport
      parentRoute: typeof AdminAiRoute
    }
    '/student/exams/$id/': {
      id: '/student/exams/$id/'
      path: '/'
      fullPath: '/student/exams/$id/'
      preLoaderRoute: typeof StudentExamsIdIndexRouteImport
      parentRoute: typeof StudentExamsIdRoute
    }
    '/admin/exams/$id/': {
      id: '/admin/exams/$id/'
      path: '/'
      fullPath: '/admin/exams/$id/'
      preLoaderRoute: typeof AdminExamsIdIndexRouteImport
      parentRoute: typeof AdminExamsIdRoute
    }
    '/student/exams/$id/take': {
      id: '/student/exams/$id/take'
      path: '/take'
      fullPath: '/student/exams/$id/take'
      preLoaderRoute: typeof StudentExamsIdTakeRouteImport
      parentRoute: typeof StudentExamsIdRoute
    }
    '/student/exams/$id/start': {
      id: '/student/exams/$id/start'
      path: '/start'
      fullPath: '/student/exams/$id/start'
      preLoaderRoute: typeof StudentExamsIdStartRouteImport
      parentRoute: typeof StudentExamsIdRoute
    }
    '/student/exams/$id/result': {
      id: '/student/exams/$id/result'
      path: '/result'
      fullPath: '/student/exams/$id/result'
      preLoaderRoute: typeof StudentExamsIdResultRouteImport
      parentRoute: typeof StudentExamsIdRoute
    }
    '/api/public/v1/students': {
      id: '/api/public/v1/students'
      path: '/api/public/v1/students'
      fullPath: '/api/public/v1/students'
      preLoaderRoute: typeof ApiPublicV1StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/stats': {
      id: '/api/public/v1/stats'
      path: '/api/public/v1/stats'
      fullPath: '/api/public/v1/stats'
      preLoaderRoute: typeof ApiPublicV1StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/leaderboard': {
      id: '/api/public/v1/leaderboard'
      path: '/api/public/v1/leaderboard'
      fullPath: '/api/public/v1/leaderboard'
      preLoaderRoute: typeof ApiPublicV1LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/quick/$code': {
      id: '/admin/students/quick/$code'
      path: '/students/quick/$code'
      fullPath: '/admin/students/quick/$code'
      preLoaderRoute: typeof AdminStudentsQuickCodeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$id/analytics': {
      id: '/admin/students/$id/analytics'
      path: '/analytics'
      fullPath: '/admin/students/$id/analytics'
      preLoaderRoute: typeof AdminStudentsIdAnalyticsRouteImport
      parentRoute: typeof AdminStudentsIdRoute
    }
    '/admin/exams/map/new': {
      id: '/admin/exams/map/new'
      path: '/exams/map/new'
      fullPath: '/admin/exams/map/new'
      preLoaderRoute: typeof AdminExamsMapNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams/$id/results': {
      id: '/admin/exams/$id/results'
      path: '/results'
      fullPath: '/admin/exams/$id/results'
      preLoaderRoute: typeof AdminExamsIdResultsRouteImport
      parentRoute: typeof AdminExamsIdRoute
    }
  }
}

interface AdminAiRouteChildren {
  AdminAiMappingRoute: typeof AdminAiMappingRoute
  AdminAiQuotasRoute: typeof AdminAiQuotasRoute
  AdminAiUsageRoute: typeof AdminAiUsageRoute
}

const AdminAiRouteChildren: AdminAiRouteChildren = {
  AdminAiMappingRoute: AdminAiMappingRoute,
  AdminAiQuotasRoute: AdminAiQuotasRoute,
  AdminAiUsageRoute: AdminAiUsageRoute,
}

const AdminAiRouteWithChildren =
  AdminAiRoute._addFileChildren(AdminAiRouteChildren)

interface AdminExamsIdRouteChildren {
  AdminExamsIdResultsRoute: typeof AdminExamsIdResultsRoute
  AdminExamsIdIndexRoute: typeof AdminExamsIdIndexRoute
}

const AdminExamsIdRouteChildren: AdminExamsIdRouteChildren = {
  AdminExamsIdResultsRoute: AdminExamsIdResultsRoute,
  AdminExamsIdIndexRoute: AdminExamsIdIndexRoute,
}

const AdminExamsIdRouteWithChildren = AdminExamsIdRoute._addFileChildren(
  AdminExamsIdRouteChildren,
)

interface AdminStudentsIdRouteChildren {
  AdminStudentsIdAnalyticsRoute: typeof AdminStudentsIdAnalyticsRoute
}

const AdminStudentsIdRouteChildren: AdminStudentsIdRouteChildren = {
  AdminStudentsIdAnalyticsRoute: AdminStudentsIdAnalyticsRoute,
}

const AdminStudentsIdRouteWithChildren = AdminStudentsIdRoute._addFileChildren(
  AdminStudentsIdRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAiRoute: typeof AdminAiRouteWithChildren
  AdminApiRoute: typeof AdminApiRoute
  AdminArchiveRoute: typeof AdminArchiveRoute
  AdminAssistantRoute: typeof AdminAssistantRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFilesRoute: typeof AdminFilesRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminMapsRoute: typeof AdminMapsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminQuestionBankRoute: typeof AdminQuestionBankRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminScanRoute: typeof AdminScanRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminExamsIdRoute: typeof AdminExamsIdRouteWithChildren
  AdminExamsAiRoute: typeof AdminExamsAiRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRouteWithChildren
  AdminExamsIndexRoute: typeof AdminExamsIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminExamsMapNewRoute: typeof AdminExamsMapNewRoute
  AdminStudentsQuickCodeRoute: typeof AdminStudentsQuickCodeRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAiRoute: AdminAiRouteWithChildren,
  AdminApiRoute: AdminApiRoute,
  AdminArchiveRoute: AdminArchiveRoute,
  AdminAssistantRoute: AdminAssistantRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFilesRoute: AdminFilesRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminMapsRoute: AdminMapsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminQuestionBankRoute: AdminQuestionBankRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminScanRoute: AdminScanRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminExamsIdRoute: AdminExamsIdRouteWithChildren,
  AdminExamsAiRoute: AdminExamsAiRoute,
  AdminStudentsIdRoute: AdminStudentsIdRouteWithChildren,
  AdminExamsIndexRoute: AdminExamsIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminExamsMapNewRoute: AdminExamsMapNewRoute,
  AdminStudentsQuickCodeRoute: AdminStudentsQuickCodeRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentExamsIdRouteChildren {
  StudentExamsIdResultRoute: typeof StudentExamsIdResultRoute
  StudentExamsIdStartRoute: typeof StudentExamsIdStartRoute
  StudentExamsIdTakeRoute: typeof StudentExamsIdTakeRoute
  StudentExamsIdIndexRoute: typeof StudentExamsIdIndexRoute
}

const StudentExamsIdRouteChildren: StudentExamsIdRouteChildren = {
  StudentExamsIdResultRoute: StudentExamsIdResultRoute,
  StudentExamsIdStartRoute: StudentExamsIdStartRoute,
  StudentExamsIdTakeRoute: StudentExamsIdTakeRoute,
  StudentExamsIdIndexRoute: StudentExamsIdIndexRoute,
}

const StudentExamsIdRouteWithChildren = StudentExamsIdRoute._addFileChildren(
  StudentExamsIdRouteChildren,
)

interface StudentExamsRouteChildren {
  StudentExamsIdRoute: typeof StudentExamsIdRouteWithChildren
  StudentExamsIndexRoute: typeof StudentExamsIndexRoute
}

const StudentExamsRouteChildren: StudentExamsRouteChildren = {
  StudentExamsIdRoute: StudentExamsIdRouteWithChildren,
  StudentExamsIndexRoute: StudentExamsIndexRoute,
}

const StudentExamsRouteWithChildren = StudentExamsRoute._addFileChildren(
  StudentExamsRouteChildren,
)

interface StudentRouteChildren {
  StudentAchievementsRoute: typeof StudentAchievementsRoute
  StudentAssistantRoute: typeof StudentAssistantRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentExamsRoute: typeof StudentExamsRouteWithChildren
  StudentFilesRoute: typeof StudentFilesRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentPointsRoute: typeof StudentPointsRoute
  StudentRewardsRoute: typeof StudentRewardsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAchievementsRoute: StudentAchievementsRoute,
  StudentAssistantRoute: StudentAssistantRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentExamsRoute: StudentExamsRouteWithChildren,
  StudentFilesRoute: StudentFilesRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentPointsRoute: StudentPointsRoute,
  StudentRewardsRoute: StudentRewardsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  StudentRoute: StudentRouteWithChildren,
  ApiPublicFcmDispatchRoute: ApiPublicFcmDispatchRoute,
  ApiPublicV1LeaderboardRoute: ApiPublicV1LeaderboardRoute,
  ApiPublicV1StatsRoute: ApiPublicV1StatsRoute,
  ApiPublicV1StudentsRoute: ApiPublicV1StudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
