/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentRewardsRouteImport } from './routes/student.rewards'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminFilesRouteImport } from './routes/admin.files'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as StudentExamsIdRouteImport } from './routes/student.exams.$id'
import { Route as AdminStudentsIdRouteImport } from './routes/admin.students.$id'
import { Route as AdminExamsAiRouteImport } from './routes/admin.exams.ai'
import { Route as AdminExamsIdRouteImport } from './routes/admin.exams.$id'
import { Route as StudentExamsIdStartRouteImport } from './routes/student.exams.$id.start'
import { Route as StudentExamsIdResultRouteImport } from './routes/student.exams.$id.result'
import { Route as AdminExamsIdResultsRouteImport } from './routes/admin.exams.$id.results'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentRewardsRoute = StudentRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFilesRoute = AdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const StudentExamsIdRoute = StudentExamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentExamsRoute,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminStudentsRoute,
} as any)
const AdminExamsAiRoute = AdminExamsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminExamsRoute,
} as any)
const AdminExamsIdRoute = AdminExamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminExamsRoute,
} as any)
const StudentExamsIdStartRoute = StudentExamsIdStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => StudentExamsIdRoute,
} as any)
const StudentExamsIdResultRoute = StudentExamsIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => StudentExamsIdRoute,
} as any)
const AdminExamsIdResultsRoute = AdminExamsIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminExamsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/ai': typeof AdminAiRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/files': typeof AdminFilesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRouteWithChildren
  '/student/messages': typeof StudentMessagesRoute
  '/student/rewards': typeof StudentRewardsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/exams/$id': typeof AdminExamsIdRouteWithChildren
  '/admin/exams/ai': typeof AdminExamsAiRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/student/exams/$id': typeof StudentExamsIdRouteWithChildren
  '/admin/exams/$id/results': typeof AdminExamsIdResultsRoute
  '/student/exams/$id/result': typeof StudentExamsIdResultRoute
  '/student/exams/$id/start': typeof StudentExamsIdStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/files': typeof AdminFilesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRouteWithChildren
  '/student/messages': typeof StudentMessagesRoute
  '/student/rewards': typeof StudentRewardsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/exams/$id': typeof AdminExamsIdRouteWithChildren
  '/admin/exams/ai': typeof AdminExamsAiRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/student/exams/$id': typeof StudentExamsIdRouteWithChildren
  '/admin/exams/$id/results': typeof AdminExamsIdResultsRoute
  '/student/exams/$id/result': typeof StudentExamsIdResultRoute
  '/student/exams/$id/start': typeof StudentExamsIdStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/ai': typeof AdminAiRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/files': typeof AdminFilesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRouteWithChildren
  '/student/messages': typeof StudentMessagesRoute
  '/student/rewards': typeof StudentRewardsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/exams/$id': typeof AdminExamsIdRouteWithChildren
  '/admin/exams/ai': typeof AdminExamsAiRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/student/exams/$id': typeof StudentExamsIdRouteWithChildren
  '/admin/exams/$id/results': typeof AdminExamsIdResultsRoute
  '/student/exams/$id/result': typeof StudentExamsIdResultRoute
  '/student/exams/$id/start': typeof StudentExamsIdStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/student'
    | '/admin/ai'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/files'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/students'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/messages'
    | '/student/rewards'
    | '/admin/'
    | '/student/'
    | '/admin/exams/$id'
    | '/admin/exams/ai'
    | '/admin/students/$id'
    | '/student/exams/$id'
    | '/admin/exams/$id/results'
    | '/student/exams/$id/result'
    | '/student/exams/$id/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/admin/ai'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/files'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/students'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/messages'
    | '/student/rewards'
    | '/admin'
    | '/student'
    | '/admin/exams/$id'
    | '/admin/exams/ai'
    | '/admin/students/$id'
    | '/student/exams/$id'
    | '/admin/exams/$id/results'
    | '/student/exams/$id/result'
    | '/student/exams/$id/start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/student'
    | '/admin/ai'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/files'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/students'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/messages'
    | '/student/rewards'
    | '/admin/'
    | '/student/'
    | '/admin/exams/$id'
    | '/admin/exams/ai'
    | '/admin/students/$id'
    | '/student/exams/$id'
    | '/admin/exams/$id/results'
    | '/student/exams/$id/result'
    | '/student/exams/$id/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/rewards': {
      id: '/student/rewards'
      path: '/rewards'
      fullPath: '/student/rewards'
      preLoaderRoute: typeof StudentRewardsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/files': {
      id: '/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminFilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/exams/$id': {
      id: '/student/exams/$id'
      path: '/$id'
      fullPath: '/student/exams/$id'
      preLoaderRoute: typeof StudentExamsIdRouteImport
      parentRoute: typeof StudentExamsRoute
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminStudentsRoute
    }
    '/admin/exams/ai': {
      id: '/admin/exams/ai'
      path: '/ai'
      fullPath: '/admin/exams/ai'
      preLoaderRoute: typeof AdminExamsAiRouteImport
      parentRoute: typeof AdminExamsRoute
    }
    '/admin/exams/$id': {
      id: '/admin/exams/$id'
      path: '/$id'
      fullPath: '/admin/exams/$id'
      preLoaderRoute: typeof AdminExamsIdRouteImport
      parentRoute: typeof AdminExamsRoute
    }
    '/student/exams/$id/start': {
      id: '/student/exams/$id/start'
      path: '/start'
      fullPath: '/student/exams/$id/start'
      preLoaderRoute: typeof StudentExamsIdStartRouteImport
      parentRoute: typeof StudentExamsIdRoute
    }
    '/student/exams/$id/result': {
      id: '/student/exams/$id/result'
      path: '/result'
      fullPath: '/student/exams/$id/result'
      preLoaderRoute: typeof StudentExamsIdResultRouteImport
      parentRoute: typeof StudentExamsIdRoute
    }
    '/admin/exams/$id/results': {
      id: '/admin/exams/$id/results'
      path: '/results'
      fullPath: '/admin/exams/$id/results'
      preLoaderRoute: typeof AdminExamsIdResultsRouteImport
      parentRoute: typeof AdminExamsIdRoute
    }
  }
}

interface AdminExamsIdRouteChildren {
  AdminExamsIdResultsRoute: typeof AdminExamsIdResultsRoute
}

const AdminExamsIdRouteChildren: AdminExamsIdRouteChildren = {
  AdminExamsIdResultsRoute: AdminExamsIdResultsRoute,
}

const AdminExamsIdRouteWithChildren = AdminExamsIdRoute._addFileChildren(
  AdminExamsIdRouteChildren,
)

interface AdminExamsRouteChildren {
  AdminExamsIdRoute: typeof AdminExamsIdRouteWithChildren
  AdminExamsAiRoute: typeof AdminExamsAiRoute
}

const AdminExamsRouteChildren: AdminExamsRouteChildren = {
  AdminExamsIdRoute: AdminExamsIdRouteWithChildren,
  AdminExamsAiRoute: AdminExamsAiRoute,
}

const AdminExamsRouteWithChildren = AdminExamsRoute._addFileChildren(
  AdminExamsRouteChildren,
)

interface AdminStudentsRouteChildren {
  AdminStudentsIdRoute: typeof AdminStudentsIdRoute
}

const AdminStudentsRouteChildren: AdminStudentsRouteChildren = {
  AdminStudentsIdRoute: AdminStudentsIdRoute,
}

const AdminStudentsRouteWithChildren = AdminStudentsRoute._addFileChildren(
  AdminStudentsRouteChildren,
)

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExamsRoute: typeof AdminExamsRouteWithChildren
  AdminFilesRoute: typeof AdminFilesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExamsRoute: AdminExamsRouteWithChildren,
  AdminFilesRoute: AdminFilesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentExamsIdRouteChildren {
  StudentExamsIdResultRoute: typeof StudentExamsIdResultRoute
  StudentExamsIdStartRoute: typeof StudentExamsIdStartRoute
}

const StudentExamsIdRouteChildren: StudentExamsIdRouteChildren = {
  StudentExamsIdResultRoute: StudentExamsIdResultRoute,
  StudentExamsIdStartRoute: StudentExamsIdStartRoute,
}

const StudentExamsIdRouteWithChildren = StudentExamsIdRoute._addFileChildren(
  StudentExamsIdRouteChildren,
)

interface StudentExamsRouteChildren {
  StudentExamsIdRoute: typeof StudentExamsIdRouteWithChildren
}

const StudentExamsRouteChildren: StudentExamsRouteChildren = {
  StudentExamsIdRoute: StudentExamsIdRouteWithChildren,
}

const StudentExamsRouteWithChildren = StudentExamsRoute._addFileChildren(
  StudentExamsRouteChildren,
)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentExamsRoute: typeof StudentExamsRouteWithChildren
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentRewardsRoute: typeof StudentRewardsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentExamsRoute: StudentExamsRouteWithChildren,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentRewardsRoute: StudentRewardsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
